apiVersion: v2
name: traefik
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: traefik
    repository: https://helm.traefik.io/traefik
    version: 28.x.x
    alias: traefik
