---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: porkbun-api-token
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgAoqI7x4GTzNa0i7MvlA78zGBZ8EAlZiYSkfZW1IQkOnH+udlpKENVV8b/VRRa73xn9n53YtpNZ/I2tf0X+KMsh445EaW9fNgwauB+6wY3ZE5v1PRzic7GW3rKhZIq2N1NkvB1yAZ9PZmSF9rT/eCmCeHJ6tbABt8ljMYShE/YLOOhANtbwTn6htboDqVZ+SMBAScds7IlkqgwnVeuoEY1dEGYow+yonuuvT+ov5kyubtzH5c5R3bOSEly28dFitRffpm7cgqIjvj17ORVqE1H/7/hSp4/URGU2+PkRlzPISPaWRk3xBHqahtADvk+3b+PoADixmxNYQNX6uMbX5uazTMLNZCMd/1Kj1ca08TTnHH2X0PnMMJXP2rZ5OoaK99DpupJIyKxLrn+WmED+UFWMSJ57+FZk+Bk6divkQRlUKFfWmzFNxx7zW2G+sl0dLki3wejb2cy601yuhun+jX0mY0Z7Wr+U/rwuw0vkzSPjdy8u11H3CgwlH6d9ADLuMDw1RjgYnXObFppqDUpcAiC4T5dVQeCyv3WJGtS6Hq8oxYA2x6IdH2fvMDP9V/81NAMhTs6OxjiNsASgvStHNFbctUhTEoN0Ow4rt8fUJcdxRdMvnwOD1VLJjwf+NIUqbm4C89DKOD+fIIkD/rjY7g2qtmHj3AHyHh/P22PAtpCWUs/Wle8DQLKrI17aYLB8L+oHO8Qi9u4Zvn/UH6Kvgp4Gcq0Nm3NaW2Tsv1yFItrjSs1LpthYJeZjFpVo+BnatEAzswFamFTT/QWmUSN7ILG3/O7rlA==
    secretKey: AgCVGrmh6mez//flgzrRSOY8Am52Rg3X7HKdbU+pTWpPuPkMR/T8b8KVN0JEbet3F5uqcD1SEJx+/fX5ORs/AiDeZD9FjaXHc9YxAbSACMDz0xnjE6E0btlV2r333bUCrLHmGEAsA77H+3D0Rg/tzSPgIZuKDeajeTSdKHvpfREgH2oKKmKqpzH+YIAJYgOJjINheseYiTi9KA5UNnhcfD+P7zZD5eMC1I/vHpdcjR+8ElSCQ+tn0ybprtY8ZSVULpgTaXfE/yMdionUpf17yy2P43qwyzBqwQqYkHh9sVHHdPGuZjYVT0M3dELfJs7E+dkdqLDhrXXXkIvxFvJIZBtCEHXYdzt3NOEmJdTIqyz2OAa92ngS0kGYZAenW4pAWZsWQu7mV39y88HXJBx04fpx9Rj9h/gTmysciYuqCPqtA+AC1gfCwaTpDQ0LegZrG9lZm1ahhaG3l2xdMru87FWcCKkRQLUmop8GtKjhJx+mvUQhrt8RG8DaaOY2bXNZzUCKhZvvAfOGXnDkH3quKUq0nzMnyK44k3uy36G2E2lfXIji2isS49BR6TTV5hmt3awvhqZwWOp0V3GrYJa9dfW5lKMUprocBoD1lwzxMd/vdWJtIJyw+5RGeLnALCqBmcci4u+to5OzBoEIY7Lmq6Fs+cjmO/hXpoFyVC34LYAswsSyFZoGJi1eVMCdFKs6sfwvLC4wZkjrXE28r6EetJHwVqzsGizEbqz2tbOPiNlsb6EM0P3nw99sFcq/j2x9754vFZeD8/JA5wVX1tWONGcP0y4jPg==
  template:
    metadata:
      creationTimestamp: null
      name: porkbun-api-token
      namespace: external-dns
