{{- if .Values.clusterIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ include "common.names.namespace" . }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.clusterIssuer.ingressClass }}
          serviceType: ClusterIP
{{- end -}}
