---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBG72pmb7ocN/Hdr6V8AkSoB7QlGrY3ArfVUuSgQdG6rzsu1/WC5Wzlsu2ZySZRlP//Sd62PWHnpEY/cTvGb8oCJC2NpOjC10tFO4Ex6f0U+QjYcSSwTfPqnWwvIFuCvOFb7xuX0+A98vpAsBg0tNsRAn/RS54A7n8zgd6LP21tRWdudUNb3nFsMyt6YShEDdLHft8RbuvKamnF8VNdIQL7dwbAX9BU9lx07DeLtt3efTS7TKsJuhEOAsyZRs08xlUlaonBUTdlIIp6j8G4DNfe/Bids6igLqOlZyXmTQLNEvKLsMdQCWrwoKC10/N5NpiKR66DiWXP3AE2UUaiy58aO1rSzs+3KqVQjzPThNXL4JlSjtu94Pxze8MAK3S2RcsLKu2pu3c6eOa9v67wLNTbMUKpLQQ7my/N9gfKJSMEB46modmDIsoPmBJSPRsTruTATa8YrOsy8/t2Q7Vo45pYK7EjK2+p5xc9PwosdVPXGcP1mxmPl7CFgd4dwp0YxRZnoLaMRZQg6DxoYVlrd9Hr1ASWy6ZQyV5zkBqcvX/Y355m8nL0GG49knfZR2wqaE6Zt6IIOU5br+MCrgfAS0g7mS3TYU+aRpzVI9gr5SfH1yLUIpiwfpjz+0AINFSby3cPRMUyRrfuxvINlAqCN0XUM3rqbMz63BdARZ9Bz+6iDW+jkafQ2alTKpBjhjpZM/E+9on8T2SXGFiL7qZXjoXN5pdrqVuSZB0YRXudrySgsFGaeosSy7Ve
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: cert-manager
    type: Opaque
