argocd:
  nameOverride: "argocd"
  fullnameOverride: "argocd"

  global:
    installCRDs: true
    domain: argocd.green-ecolution.de

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: argocd.green-ecolution.de
          paths:
            - /
      tls: true
