argocd:
  nameOverride: "argocd"
  fullnameOverride: "argocd"

  global:
    installCRDs: true
    domain: argocd.green-ecolution.de

  server:
    ingress:
      enabled: true
      ingressClassName: traefik-ingress-controller
      annotations:
        cert-manager.io/cluster-issuer: "cert-manager"
        kubernetes.io/ingress.class: traefik-ingress-controller
      hosts:
        - host: argocd.green-ecolution.de
          paths:
            - /
      tls: true
