---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgBuFKwpqHGIC3pMywq+/7IsEmg9e7wsj4n9gd4uRdyMaekVgsNtufhifCa6HI58MEMlNIX8uON6PylJhQQw3gKNCyayyzN/qUifdv/ncYDiKxAb05wg+88gUQcEzTAiCcfY0ioSDjWaeKH3Wsnj97n3cGGpInTZ5t6e/yqMUK46Xp9iP8hRcaVZsJ0oA0gTuj9hvYw8z43D+Eoj6MY+mLeEH/PgfTLL1HhJcdFnjT4zovLIh0DiSpIy+5JpfhcLaM+XjDE+DEGn08eF4jLkSHA8WgbNU61QO6bctVjry2SBTcmJC923kcdCXKb61L3ZnZ9GRer7kAw/XwodAg8hhAa21iI6S8DmXNiCmPuDFckGS+No7wYZw0YAwiw2tlAcSsNyPcoeGAb+rtHk82Tb2Hyq7J67BCRNhIUXJnfPaHX9jDSVYnQgcBfcemRc2pOACVk3yo/EtGLrLHNAkfzuHhkWFBH7qIzQdLOuuiz6GzGtP81atxR/5Krw3kmX1aAbmzJBEx8c8wry5nbCIJE1ZvD0fxw+NDryqOZNijdJaLfdXfpucSinNeLsjRIg4LofGfecEcK2AhiP2QtJNpMYLd9Be3kxo7YDJ0X2RrqlxQPvuGM/Xyk0SXwNpfCTfDghzFmm6haRjQ4JX9xOL9jdL9OTPY4KR38xSXhiLYy4Mz1NFVXTR3pMwTRHI4zHsao83CxlJ2KA7cxjaUasFQdkHe8ZsMeFWg6sbkbGQ4sjhkRfacsYrQzOwMsP
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin-token
      namespace: vaultwarden
