apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

appVersion: "1.12.1"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x

  - name: cert-manager
    version: 0.12.11
    repository: https://charts.bitnami.com/bitnami
    alias: cert-manager
    condition: cert-manager.enabled
